### ISSUE TITLE
use GitHub Actions, GitLab-CI, or other CI service to run this

### ISSUE THREAD

**Issue by eighthave** [eagletmt/android-repository-history#1]
This is a nice history!  I see that it recently stopped working.  It would be really easy to get this working on https://gitlab.com by importing this repo there, then adding _.gitlab-ci.yml_ with this contents:

```yaml
image: golang:1.10-stretch
script:
  - go build update.go
  - apt update && apt install -y ca-certificates git
  - ./auto.sh
```

I imagine using GitHub Actions would also not be hard.  FYI, I discovered this because I did something similar:
* https://gitlab.com/fdroid/gradle-transparency-log/
* https://gitlab.com/fdroid/android-sdk-transparency-log/
